u = User.create!(first_name: "CJ", last_name: "Wilson", email: "cj@cj.com", password: "password")
c = Customer.create(first_name: "Joe", last_name: "Test", email: "christopher.wilson.jr@gmail.com")
# r = Racket.create!(owner_id: 1)
# s = Stringset.create!(racket_id: 1)

#Tennis
Stringset.create!(brand: "Babolat", description: "VS Gut", game: "Tennis", restring_price: 65)
Stringset.create!(brand:"Babolat", description: "Tonic", game: "Tennis", restring_price: 50)
Stringset.create!(brand:"Babolat", description: "Xcel", game: "Tennis", restring_price: 37)
Stringset.create!(brand:"Babolat", description: "Pro Hur Tr", game: "Tennis", restring_price: 37)
Stringset.create!(brand:"Babolat", description: "Xcel/PHT", game: "Tennis", restring_price: 38)
Stringset.create!(brand:"Babolat", description: "Pro Hur", game: "Tennis", restring_price: 33)
Stringset.create!(brand:"Babolat", description: "RPM", game: "Tennis", restring_price: 39)
Stringset.create!(brand:"Babolat", description: "RPM/VS", game: "Tennis", restring_price: 52)

Stringset.create!(brand:"Gamma", description: "Live Wi. Prof", game: "Tennis", restring_price: 40)
Stringset.create!(brand:"Gamma", description: "RX", game: "Tennis", restring_price: 36)
Stringset.create!(brand:"Gamma", description: "Live Wire XP", game: "Tennis", restring_price: 35)
Stringset.create!(brand:"Gamma", description: "TNT", game: "Tennis", restring_price: 31)
Stringset.create!(brand:"Gamma", description: "TNT Pro Plus", game: "Tennis", restring_price: 34)
Stringset.create!(brand:"Gamma", description: "Marathon", game: "Tennis", restring_price: 32)
Stringset.create!(brand:"Gamma", description: "Ruff", game: "Tennis", restring_price: 32)
Stringset.create!(brand:"Gamma", description: "Syn Gut", game: "Tennis", restring_price: 25)
Stringset.create!(brand:"Gamma", description: "Glide Hybrid", game: "Tennis", restring_price: 40)

Stringset.create!(brand:"Solinco", description: "Tour Bite", game: "Tennis", restring_price: 32)
Stringset.create!(brand:"Solinco", description: "Revolution", game: "Tennis", restring_price: 32)

Stringset.create!(brand:"Luxilon", description: "ALU/Rgh", game: "Tennis", restring_price: 36)
Stringset.create!(brand:"Luxilon", description: "Timo", game: "Tennis", restring_price: 36)
Stringset.create!(brand:"Luxilon", description: "Ace", game: "Tennis", restring_price: 36)
Stringset.create!(brand:"Luxilon", description: "ALU Orig.", game: "Tennis", restring_price: 36)
Stringset.create!(brand:"Luxilon", description: "4G", game: "Tennis", restring_price: 38)

Stringset.create!(brand:"Technifibre", description: "X-One Bi", game: "Tennis", restring_price: 36)
Stringset.create!(brand:"Technifibre", description: "NRG2", game: "Tennis", restring_price: 34)
Stringset.create!(brand:"Technifibre", description: "Red Code", game: "Tennis", restring_price: 34)
Stringset.create!(brand:"Technifibre", description: "Black Code", game: "Tennis", restring_price: 34)
Stringset.create!(brand:"Technifibre", description: "HDX Tour", game: "Tennis", restring_price: 42)

Stringset.create!(brand:"Head", description: "Velocity MLT", game: "Tennis", restring_price: 31)
Stringset.create!(brand:"Head", description: "Intellistring", game: "Tennis", restring_price: 35)
Stringset.create!(brand:"Head", description: "Intellitour", game: "Tennis", restring_price: 33)
Stringset.create!(brand:"Head", description: "Sonic Pro", game: "Tennis", restring_price: 33)
Stringset.create!(brand:"Head", description: "FXP", game: "Tennis", restring_price: 31)
Stringset.create!(brand:"Head", description: "FXP Tour", game: "Tennis", restring_price: 34)
Stringset.create!(brand:"Head", description: "Sonic Pro Edge", game: "Tennis", restring_price: 33)
Stringset.create!(brand:"Head", description: "Hawk", game: "Tennis", restring_price: 36)
Stringset.create!(brand:"Head", description: "Gravity", game: "Tennis", restring_price: 39)
Stringset.create!(brand:"Head", description: "Lynx", game: "Tennis", restring_price: 33)

Stringset.create!(brand:"Prince", description: "Premier", game: "Tennis", restring_price: 35)
Stringset.create!(brand:"Prince", description: "Problend", game: "Tennis", restring_price: 32)
Stringset.create!(brand:"Prince", description: "Lightning XX", game: "Tennis", restring_price: 28)
Stringset.create!(brand:"Prince", description: "Syn Gut", game: "Tennis", restring_price: 25)
Stringset.create!(brand:"Prince", description: "Prm Touch", game: "Tennis", restring_price: 35)
Stringset.create!(brand:"Prince", description: "Prm Control", game: "Tennis", restring_price: 32)
Stringset.create!(brand:"Prince", description: "Warrior Hyb", game: "Tennis", restring_price: 33)
Stringset.create!(brand:"Prince", description: "Tour XC", game: "Tennis", restring_price: 32)
Stringset.create!(brand:"Prince", description: "Tour XS", game: "Tennis", restring_price: 34)
Stringset.create!(brand:"Prince", description: "Tour XP", game: "Tennis", restring_price: 36)

Stringset.create!(brand:"Wilson", description: "NXT Power", game: "Tennis", restring_price: 40)
Stringset.create!(brand:"Wilson", description: "NXT", game: "Tennis", restring_price: 38)
Stringset.create!(brand:"Wilson", description: "Sensation", game: "Tennis", restring_price: 32)
Stringset.create!(brand:"Wilson", description: "Champ. Chc", game: "Tennis", restring_price: 48)
Stringset.create!(brand:"Wilson", description: "NXT Duo II", game: "Tennis", restring_price: 38)
Stringset.create!(brand:"Wilson", description: "Ripspin", game: "Tennis", restring_price: 31)
Stringset.create!(brand:"Wilson", description: "Optimus", game: "Tennis", restring_price: 34)

#Racquetball
Stringset.create!(brand:"Gamma", description: "Syn", game: "Racquetball", restring_price: 25)
Stringset.create!(brand:"Head", description: "Mega", game: "Racquetball", restring_price: 31)
Stringset.create!(brand:"Ekt.", description: "Prm Pr", game: "Racquetball", restring_price: 36)
Stringset.create!(brand:"E Force", description: "Oxy.", game: "Racquetball", restring_price: 36)
Stringset.create!(brand:"Prince", description: "XX", game: "Racquetball", restring_price: 28)

#Badminton
Stringset.create!(brand:"Yonex", description: "BG 65", game: "Badminton", restring_price: 32)

#Squash
Stringset.create!(brand:"Gamma", description: "Syn", game: "Squash", restring_price: 25)
Stringset.create!(brand:"Tec.", description: "NRG", game: "Squash", restring_price: 34)
Stringset.create!(brand:"Gamma", description: "TNT", game: "Squash", restring_price: 31)
Stringset.create!(brand:"Ash.", description: "Supernk", game: "Squash", restring_price: 30)
Stringset.create!(brand:"Ash.", description: "Ultrank", game: "Squash", restring_price: 33)
Stringset.create!(brand:"Tec.", description: "305", game: "Squash", restring_price: 33)
Stringset.create!(brand:"Dunlop", description: "Expl.", game: "Squash", restring_price: 32)
